### ISSUE TITLE
Implement a header value part generator

### ISSUE THREAD

**Issue by ocReaper** [ocReaper/wp-server-timing#1]
Implement a function that accepts 4 parameters: `name(string)`, `description(string)`, `startTime(int)`, `endTime(int|null)` and assembles a header value part in the following format `{name};desc="{description}";dur={(endTime-startTime)*1000}`. If endTime is `null` handle it as `microtime(true)`.

**Comment by FarkasJanos** [comment]
Could you assign it to me?
